### ISSUE TITLE
add build tooling and test

### ISSUE THREAD

**Issue by wvanderdeijl** [oracle/oraclejet#1]
Let me start by congratulating you with open sourcing Oracle JET. 

Currently this repo is just a source drop of a "packaged" release. Please also add the build tooling (gulp. grunt, or something similar) and the automated tests you use to produce Oracle JET.

This would make it feel more like a true open source project and allows the community to take JET and extend it with unexpected (and hopefully) beautiful features.

**Comment by brunoborges** [comment]
@GeertjanWielenga is there any plan to do this?

**Comment by peppertech** [comment]
There are plenty of things we still need to do with the quality of the open source project and we are working toward that higher level.  It will take us a little while longer to get there.  

We wanted to get the core toolkit out and open sourced as quickly as possible instead of sitting on it internally until we had it all perfect.  I hope you and others can appreciate this approach

While the build and test code is not currently included, this shouldn't stop anyone from working with the code that is there to provide their own new components, themes, validators, converters, and many other possible ways of extending the JET toolkit.

I will be adding a section to the FAQ shortly that will hopefully provide a better understanding of what we are planning to do going forward and just how quickly we think we can get there.
