### ISSUE TITLE
Bower consumption of OJ

### ISSUE THREAD

**Issue by tomasAlabes** [oracle/oraclejet#16]
I see an inconsistency between the dependencies defined in the bower json and the ones needed by oj. In the bower.json you see jqueryui but then a jqueryui-amd is needed, which isn't included in jet nor available in bower (in the oj generator is part of the src, which doesn't folow the 3rd party
deps idea of bower).

And it's bringing a lot of conflicts to our paths resolutions, as require tries to reuse paths if found.

  "jquery-ui": "../../../bower_components/jquery-ui/jquery-ui",
  "jqueryui-amd": "../../../bower_components/jquery-ui/ui"

requirejs resolves the "jquery-ui" in the 2nd path as the one in the 1st,
messing the paths resolution. And we need to support these usages:

require('jquery-ui') -> load jqueryui
require('jqueryui-amd/sortable')

If bower is not officially supported I would mention it in the documentation here.
(issue #24348023 for Oracle's)

Thanks

**Comment by peppertech** [comment]
The issue you are running into a result of jQueryUI changing the location of AMD based modules with their 1.12.0 release (which was required because of the jQuery 3.1.0 changes).

While bower should still work for this, we will be moving away from it with the v3.0.0 release of JET.  We will be using npm for everything going forward.  Bower will be announced as deprecated, but will not be removed as per the deprecation policy for one year.  It should be a lot easier to just have one package manager going forward with npm.

**Comment by peppertech** [comment]
We have removed Bower from the command line tools with the release of v3.0.0 of JET.  I'm going to close this as a non-issue going forward since we will not be using Bower any longer for JET.  Everything is npm based now.
