### ISSUE TITLE
Samples folder should contain extracted projects

### ISSUE THREAD

**Issue by brunoborges** [oracle/oraclejet#2]
The samples folder has at the moment 3 ZIP files. These should be kept extracted in GitHub, and instead the ZIPs should be part of a release cycle.

**Comment by brunoborges** [comment]
// @GeertjanWielenga

**Comment by peppertech** [comment]
Hi Bruno,

The samples are currently just shells that are used by the Yeoman Generator at the moment to setup the structure of the application, and then the actual JET libraries are added via a bower install and bowercopy task in the generator.

We will look into providing both the .zip for the generator, as well as an expanded version that has it's own Gruntfile so that they can be pulled and built on their own.

There are plenty of things we still need to do with the quality of the open source project and we are working toward that higher level.  It will take us a little while longer to get there.  

We wanted to get the core toolkit out and open sourced as quickly as possible instead of sitting on it internally until we had it all perfect.  I hope you and others can appreciate this approach

**Comment by brunoborges** [comment]
Hi @peppertech, I do and I'm sure everyone does appreciate JET being open sourced. But as with all things, there is a minimum expectation that some things will be done right from day one. Hosting binaries, even if just ZIP files, on a git repository, is against any and every best practice (including some policies).

What I'd expect from this JET 2.0 release as an Open Source project, would be to see these ZIPs as part of a "2.0 release", properly handled and hosted under the [GitHub Releases](https://help.github.com/articles/creating-releases/) feature.

**Comment by peppertech** [comment]
You are absolutely right Bruno.  That was an oversight on our part of putting them in the /samples folder.  We are working to correct that.

**Comment by peppertech** [comment]
A quick follow on this.  I have been corrected in my statement that the generator uses the zips in the /samples directory.  It does not.  It correctly uses the Releases location and the existence of the .zip files in the /samples directory is a complete error where we didn't remove them internally before we made the push.  They are not used at all from this location, from what I've been told.

**Comment by brunoborges** [comment]
Is it possible to push back the samples in expanded mode?

**Comment by blm7** [comment]
Hi @brunoborges.  They're available for download as part of the release here: https://github.com/oracle/oraclejet/releases/tag/2.0.0.  They're not really part of the core JET project, so we don't push the expanded source here.  They're hosted here as part of the release as part of our JET tooling and scaffolding package.  That said, we're likely to move them to their own packages in future releases because they're not really part of the core JET project.

**Comment by brunoborges** [comment]
@blm7 Yeah, an oraclejet-samples repository is a great idea. :+1:

**Comment by peppertech** [comment]
Going to close this issue now that we have the /samples directory removed.  We'll look into the future samples repos instead.

**Comment by brunoborges** [comment]
Thanks @peppertech and @blm7 for all your support.
