### ISSUE TITLE
ojtable issues and backward compatibility breaking (version 3.0.0)

### ISSUE THREAD

**Issue by xsh525** [oracle/oraclejet#25]
In ojtable.js
1.The this._DISABLED is undefined in function _isTableSortable, shouldn't it be this._OPTION_DISABLED?
2. sortable="none" now will be treate as enable of sort, it's a backward compatibility breaking

**Comment by peppertech** [comment]
internal/private APIs (those starting with _ ) are not for public use and have no guarantee that they will not change or be deleted without notice.  They are private for a reason.

**Comment by xsh525** [comment]
I did not directly use these apis, I just found this issue by debugging, after upgrade ojet from 2.3 to 3.0

**Comment by kentarokinebuchi** [comment]
"none" was never meant to be a valid value for sortable. The JSDoc has always listed "enabled" and "disabled":

http://www.oracle.com/webfolder/technetwork/jet/jsdocs/oj.ojTable.html#columnsDefault.sortable

There was a bug in the code which used "none" however, as you pointed out, the fix for that bug has a typo so it should be this._OPTION_DISABLED. This issue will be fixed.

**Comment by kentarokinebuchi** [comment]
Also, the "this._OPTION_DISABLED" typo issue ONLY affects whether the sort option is displayed on context menu right click on a column. The sort icon on the column header itself will not be displayed if sortable is set to "none" or "disabled". In addition, the sort asc/desc menu items will be disabled if sortable is set to "none" or "disabled" so this issue should only result a very minor problem. It's not really a backward compatibility breaking problem.

**Comment by xsh525** [comment]
Thanks for you explaination
