### ISSUE TITLE
Simplify Knockout Bindings

### ISSUE THREAD

**Issue by RichiCoder1** [oracle/oraclejet#5]
Would be great to do this:
```html
    <input id="input" data-bind="ojInputText: {
            value: 'text',
            required: isRequired, 
            help: {definition: helpDef(), source:helpSource()}}">
```
instead of
```html
    <input id="input" data-bind="ojComponent: {
            component: 'ojInputText', 
            value:'text',
            required: isRequired, 
            help: {definition: helpDef(), source:helpSource()}}">
```
and
```html
<oj-tree id="tree" style="float:left;width: 180px;height: auto;" params="selectionMode: 'multiple', data: { data: getJson }" />
```
instead of
```html
<div id="tree" style="float:left;width: 180px;height: auto;"
               data-bind="ojComponent:
               {
                 component: 'ojTree',
                 selectionMode: 'multiple',
                 data:{data: getJson}
               }">
</div>
```

**Comment by danibram** [comment]
Hi guys! We released something in the meantime that can help. https://github.com/bpmsoasolutions/jet-komponents
All comments, improvements or issues are welcome! Thanks

**Comment by GeertjanWielenga** [comment]
Very cool and interesting.

**Comment by peppertech** [comment]
Well done Daniel.  Great to see devs getting involved and creating their
own solutions.  One word of advice/caution that I can see.  If the JET
project comes up with a solution of their own, it will end up overwriting
what you have provided because you are reusing the existing oj-xxx
namespaced component names.  It may be safer in the long run to have your
component solution use something like ojk-xxx instead. That "oj" namespace
is used extensively throughout the project code from JavaScript to CSS so
that it doesn't conflict with any existing code that may have a similar
name.

I'll tell you now that Oracle is planning to do something along these lines
later this year and it will conflict. It's not the same approach, but it
would conflict with the namespace that you have chosen.

Again, great work and a very big welcome to the JET community!

**Comment by danibram** [comment]
Hi @peppertech  and @GeertjanWielenga. First of all thanks for your comments. Taking this in cosideration Im finishing a new release with the prefixes renamed to "ojk-".
Thanks for your time

**Comment by brunoborges** [comment]
@danibram can we close this issue?

**Comment by danibram** [comment]
yes, thanks!
