### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by RobertoMalatesta** [oracle/oraclejet#6]
Some questions for the Oracle staff:

1 ) what is the license of Oracle Alta UI? 
1.1 is it Open Source as well? 
1.2 If yes, where's the repo?
1.3 If not, are you planning to release it?

2) are you considering Typescript support -- like,to different extents,  React, Angular2, Dojo2 are doing ?

Thank you in advance

Roberto

**Comment by peppertech** [comment]
Hi Roberto,

Alta UI is a CSS based look and feel.  It comes with Oracle JET as part of the CSS/SCSS libraries.  It's more of a concept than a product.  Take a look at http://altaui.com  

There isn't a repository, because there isn't anything to put in it really.  Alta is a UI standard that Oracle products use, and can also be used by anyone.

Typescript is not something that JET itself will include for now, but there shouldn't be any reason that you couldn't use it in a JET page.  There are a lot of resources out on the Internet for getting TypeScript to work with both RequireJS and Knockout.  That is what I would imagine will be the first thing to work out.  JET doesn't introduce any proprietary concepts. It's pure JavaScript, HTML5, and CSS3 and follows the specs as closely as possible so you shouldn't run into to many problems.

**Comment by RobertoMalatesta** [comment]
Hi John (@peppertech)
Thank you for the prompt and clarifying response.
I will follow the project closely,
keep up the good work.

R
